import { SlideContent, SlideElement } from '../../types/slide';
import { ThemeConfig } from '../../types/theme';

const stripHtml = (value: string): string => {
  return value.replace(/<[^>]*>/g, '');
};

const getElementText = (element: SlideElement): string => {
  if (typeof element.content === 'string') {
    return stripHtml(element.content);
  }
  if (Array.isArray(element.content)) {
    return element.content.map(item => stripHtml(String(item))).join('\n');
  }
  return '';
};

export const exportToPPTX = async (slides: SlideContent[], theme?: ThemeConfig): Promise<Blob> => {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    throw new Error('PPTX 导出仅在浏览器环境中可用');
  }

  const pptxModule = await import('pptxgenjs');
  const PptxGenJS = pptxModule.default as any;
  const pptx = new PptxGenJS();

  // 设置文档元数据
  pptx.title = 'Md2Slide Presentation';
  pptx.subject = 'Created with Paper2Slide';

  const primaryColor = theme?.primaryColor || '#4f46e5';
  const bgColor = theme?.colors?.background || '#ffffff';
  const textColor = theme?.colors?.text || '#000000';

  // 1. 标题页
  const titleSlide = pptx.addSlide();
  titleSlide.background = { fill: bgColor };
  
  titleSlide.addText('Md2Slide Presentation', {
    x: 1,
    y: 2,
    w: 8,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: primaryColor,
    align: 'center',
  });

  titleSlide.addText('Generated by Paper2Slide', {
    x: 1,
    y: 3.5,
    w: 8,
    h: 0.5,
    fontSize: 20,
    color: textColor,
    align: 'center',
  });

  // 2. 目录页
  const tocSlide = pptx.addSlide();
  tocSlide.background = { fill: bgColor };
  tocSlide.addText('目录 / Table of Contents', {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.8,
    fontSize: 32,
    bold: true,
    color: primaryColor,
  });

  const tocLines = slides.map((slide, index) => {
    const title = slide.title ? stripHtml(slide.title) : `Slide ${index + 1}`;
    return { text: title, options: { bullet: true, indentLevel: 0, fontSize: 16, color: textColor } };
  });

  // 分页处理目录
  const itemsPerPage = 10;
  for (let i = 0; i < tocLines.length; i += itemsPerPage) {
    const slide = i === 0 ? tocSlide : pptx.addSlide();
    if (i > 0) {
      slide.background = { fill: bgColor };
      slide.addText('目录 (续)', { x: 0.5, y: 0.5, w: 9, h: 0.8, fontSize: 32, bold: true, color: primaryColor });
    }
    
    slide.addText(tocLines.slice(i, i + itemsPerPage), {
      x: 0.8,
      y: 1.5,
      w: 8.5,
      h: 5,
      valign: 'top',
    });
  }

  // 3. 内容页
  for (const slide of slides) {
    const current = pptx.addSlide();
    current.background = { fill: bgColor };
    
    const title = slide.title ? stripHtml(slide.title) : '';
    if (title) {
      current.addText(title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.8,
        fontSize: 28,
        bold: true,
        color: primaryColor,
        border: { type: 'none', pt: 1, color: primaryColor }
      });
    }

    let currentY = 1.2;
    const bodyItems: any[] = [];

    for (const element of slide.elements) {
      if (!element || element.type === 'title') continue;

      if (element.type === 'image') {
        const url = element.content as string;
        if (url && url.startsWith('http')) {
          try {
            current.addImage({
              path: url,
              x: 5.5,
              y: 1.5,
              w: 4,
              h: 3,
            });
          } catch (e) {
            console.warn('Failed to add image to PPTX:', e);
          }
        }
        continue;
      }

      if (element.type === 'list') {
        const items = Array.isArray(element.content) ? element.content : [element.content];
        items.forEach(item => {
          bodyItems.push({ 
            text: stripHtml(String(item)), 
            options: { bullet: true, fontSize: 18, color: textColor, margin: [5, 0, 5, 0] } 
          });
        });
        continue;
      }

      const text = getElementText(element);
      if (text) {
        let fontSize = 18;
        let isBold = false;
        if (element.type === 'subtitle') {
          fontSize = 22;
          isBold = true;
        } else if (element.type === 'code') {
          fontSize = 14;
        }

        bodyItems.push({ 
          text, 
          options: { fontSize, bold: isBold, color: textColor, margin: [5, 0, 5, 0] } 
        });
      }
    }

    if (bodyItems.length > 0) {
      current.addText(bodyItems, {
        x: 0.7,
        y: currentY,
        w: 5, // 如果有图片，宽度缩小
        h: 5.5,
        valign: 'top',
      });
    }
  }

  const blob = await pptx.write('blob');
  return blob as Blob;
};

export const downloadPPTX = async (slides: SlideContent[], theme?: ThemeConfig) => {
  const blob = await exportToPPTX(slides, theme);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `presentation-${new Date().getTime()}.pptx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

